<a href="https://colab.research.google.com/github/sravs1407/machine-learning/blob/main/lab3_%26lab4_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv("/content/p3.csv")
df=pd.DataFrame(df)
df

     outlook temperature humidity  windy class
0      sunny         hot     high  False     n
1      sunny         hot     high   True     n
2   overcast         hot     high  False     p
3       rain        mild     high  False     p
4       rain        cool   normal  False     p
5       rain        cool   normal   True     n
6   overcast        cool   normal   True     p
7      sunny        mild     high  False     n
8      sunny        cool   normal  False     p
9       rain        mild   normal  False     p
10     sunny        mild   normal   True     p

In [ ]:
def naivebayies(df):
  temp={"sunnyp":0,"sunnyn":0,"overcastp":0,"overcastn":0,"rainp":0,"rainn":0,"hotp":0,"hotn":0,"mildp":0,"mildn":0,"coolp":0,"cooln":0,"highp":0,"highn":0,"normalp":0,"normaln":0,"Truep":0,"Truen":0,"Falsep":0,"Falsen":0}
  col=len(df.columns)
  pos=0
  neg=0
  for i in range(len(df.index)):
    for j in range(col-1):
      if(df.loc[i,"class"]=='p'):
         s=str(df.iloc[i,j])+'p'
         temp[s]+=1
         pos+=1
      else:
        s=str(df.iloc[i,j])+"n"
        temp[s]+=1
        neg+=1
  return temp,pos,neg;
lis,pos,neg=naivebayies(df)
print(lis)
print(pos/len(df.index))

{'sunnyp': 2, 'sunnyn': 3, 'overcastp': 2, 'overcastn': 0, 'rainp': 3, 'rainn': 1, 'hotp': 1, 'hotn': 2, 'mildp': 3, 'mildn': 1, 'coolp': 3, 'cooln': 1, 'highp': 2, 'highn': 3, 'normalp': 5, 'normaln': 1, 'Truep': 2, 'Truen': 2, 'Falsep': 5, 'Falsen': 2}
2.5454545454545454

In [ ]:
testing=pd.read_csv("/content/testp3.csv")
testing

    outlook temperature humidity   wind
0  overcast        mild     high   True
1  overcast         hot   normal  False
2      rain        mild     high   True

In [ ]:
def testingdata(test,pos,neg,temp,length):
  py=pos/length
  pn=neg/length
  print(py,pn)
  res=[]
  for i in range(len(test.index)):
    res1=py
    res2=pn
    for j in range(len(test.columns)-1):
      res1=res1*(temp[str(df.iloc[i,j])+'p']/pos)
      res2=res2*(temp[str(df.iloc[i,j])+'n']/neg)
    print(res1,res2)
    if(res1>res2):
      res.append('p')
    else:
      res.append('n')
  return res;
out=testingdata(testing,pos,neg,lis,len(df.index))
print(out)

2.5454545454545454 1.4545454545454546
0.00046382189239332086 0.006392045454545454
0.00046382189239332086 0.006392045454545454
0.00046382189239332086 0.0
['n', 'n', 'p']

In [2]:
import pandas as pd
df=pd.read_csv("/content/lab4.csv")
df=pd.DataFrame(df)
df

                                    text class
0                   I love this sandwich   pos
1               this is an amazing place   pos
2     I feel very good about these beers   pos
3                   this is my best work   pos
4                   what an awesome view   pos
5          I do not like this restaurant   neg
6               I am tired of this stuff   neg
7                 I can't deal with this   neg
8                   he is my sworn enemy   neg
9                    my boss is horrible   neg
10              this is an awesome place   pos
11  I donot like the taste of this juice   neg
12                       I love to dance   pos
13     I am sick and tired of this place   neg
14                  what a great holiday   pos
15        that is a bad locality to stay   neg
16        we will have good fun tomorrow   pos
17      I went to my enemy's house today   neg

In [13]:
def vocab(df):
  l=[]
  for i in range(0,11):
    for j in (df.loc[i,"text"]).split():
      if j not in l:
        l.append(j)
  return l;
voc=vocab(df)
print(voc)

['I', 'love', 'this', 'sandwich', 'is', 'an', 'amazing', 'place', 'feel', 'very', 'good', 'about', 'these', 'beers', 'my', 'best', 'work', 'what', 'awesome', 'view', 'do', 'not', 'like', 'restaurant', 'am', 'tired', 'of', 'stuff', "can't", 'deal', 'with', 'he', 'sworn', 'enemy', 'boss', 'horrible']

In [17]:
from re import S
def count(temp,voc):
  l=[]
  s=0
  index=0
  for i in voc:
    c=0;
    if i in temp:
      for j in temp:
        if (j==i):
          c+=1
    s+=c
    l.append(c)
  return l,s;
def docs(df,voc):
  docpos={}
  docneg={}
  poscount=0
  negcount=0
  for i in range(0,11):
    temp=(df.loc[i,"text"]).split()
    lis,s=count(temp,voc)
    if df.loc[i,"class"]=="pos":
      docpos[i+1]=lis
      poscount+=s
    else:
      docneg[i+1]=lis
      negcount+=s
  return docpos,docneg,poscount,negcount;
docpos,docneg,poscount,negcount=docs(df,voc)
print(docpos,docneg)
print(poscount,negcount)

{1: [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 2: [0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 3: [1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 4: [0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 5: [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 11: [0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]} {6: [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 7: [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], 8: [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0], 9: [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0], 10: [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]}
30 26

In [26]:
def prior(voc,doc,count):
  dic={}
  for i in range(len(voc)):
    dic[voc[i]]=0
    for temp in doc.values():
      dic[voc[i]]+=temp[i]
    dic[voc[i]]=(dic[voc[i]]+1)/(count+len(voc))
  return dic
priprobpos=prior(voc,docpos,poscount)
priprobneg=prior(voc,docneg,negcount)
print(priprobpos)
print(priprobneg)

{'I': 0.045454545454545456, 'love': 0.030303030303030304, 'this': 0.07575757575757576, 'sandwich': 0.030303030303030304, 'is': 0.06060606060606061, 'an': 0.06060606060606061, 'amazing': 0.030303030303030304, 'place': 0.045454545454545456, 'feel': 0.030303030303030304, 'very': 0.030303030303030304, 'good': 0.030303030303030304, 'about': 0.030303030303030304, 'these': 0.030303030303030304, 'beers': 0.030303030303030304, 'my': 0.030303030303030304, 'best': 0.030303030303030304, 'work': 0.030303030303030304, 'what': 0.030303030303030304, 'awesome': 0.045454545454545456, 'view': 0.030303030303030304, 'do': 0.015151515151515152, 'not': 0.015151515151515152, 'like': 0.015151515151515152, 'restaurant': 0.015151515151515152, 'am': 0.015151515151515152, 'tired': 0.015151515151515152, 'of': 0.015151515151515152, 'stuff': 0.015151515151515152, "can't": 0.015151515151515152, 'deal': 0.015151515151515152, 'with': 0.015151515151515152, 'he': 0.015151515151515152, 'sworn': 0.015151515151515152, 'enemy': 0.015151515151515152, 'boss': 0.015151515151515152, 'horrible': 0.015151515151515152}
{'I': 0.06451612903225806, 'love': 0.016129032258064516, 'this': 0.06451612903225806, 'sandwich': 0.016129032258064516, 'is': 0.04838709677419355, 'an': 0.016129032258064516, 'amazing': 0.016129032258064516, 'place': 0.016129032258064516, 'feel': 0.016129032258064516, 'very': 0.016129032258064516, 'good': 0.016129032258064516, 'about': 0.016129032258064516, 'these': 0.016129032258064516, 'beers': 0.016129032258064516, 'my': 0.04838709677419355, 'best': 0.016129032258064516, 'work': 0.016129032258064516, 'what': 0.016129032258064516, 'awesome': 0.016129032258064516, 'view': 0.016129032258064516, 'do': 0.03225806451612903, 'not': 0.03225806451612903, 'like': 0.03225806451612903, 'restaurant': 0.03225806451612903, 'am': 0.03225806451612903, 'tired': 0.03225806451612903, 'of': 0.03225806451612903, 'stuff': 0.03225806451612903, "can't": 0.03225806451612903, 'deal': 0.03225806451612903, 'with': 0.03225806451612903, 'he': 0.03225806451612903, 'sworn': 0.03225806451612903, 'enemy': 0.03225806451612903, 'boss': 0.03225806451612903, 'horrible': 0.03225806451612903}

In [32]:
def classcount(df):
  poscount=0
  negcount=0
  for i in range(0,11):
    if (df.loc[i,"class"])=="pos":
      poscount+=1
    else:
      negcount+=1
  return poscount,negcount;
def test(df,dicpos,dicneg,p,n):
  l=[]
  for i in range(10,len(df.index)):
    print(df.loc[i,"text"])
    pos=p
    neg=n
    for j in (df.loc[i,"text"]).split():
      if  j in dicpos.keys():
         pos*=dicpos[j]
      if  j in dicneg.keys():
         neg*=dicneg[j]
    if(pos>neg):
      l.append("pos")
    else:
      l.append("neg")
  return l;
p,n=classcount(df)
tes=test(df,priprobpos,priprobneg,p,n)
print(tes)

this is an awesome place
I donot like the taste of this juice
I love to dance
I am sick and tired of this place
what a great holiday
that is a bad locality to stay
we will have good fun tomorrow
I went to my enemy's house today
['pos', 'neg', 'pos', 'neg', 'pos', 'pos', 'pos', 'neg']

In [33]:
def cal(df,l):
  c=0
  tp=0
  tn=0
  fp=0
  fn=0
  for i in range(10,len(df.index)):
    if(l[c]==df.loc[i,"class"]):
      if l[c]=="pos":
        tp+=1
      else:
        tn+=1
    else:
      if l[c]=="pos":
        fn+=1
      else:
        fp+=1
  return tp,tn,fp,fn;
tp,tn,fp,fn=cal(df,tes)
recall=tp/(tp+fn)
accuracy=(tp+tn)/(tp+tn+fp+fn)
precision=tp/(tp+fp)
print("recall=",recall," accuracy=",accuracy," precision=",precision)

recall= 0.5  accuracy= 0.5  precision= 1.0